project:
  type: website
  output-dir: docs

website:
  title: "Matthew J Prado Portfolio"
  google-analytics: "G-SRJF0PFMLY"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Resume

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



