project:
  type: website
  output-dir: docs

website:
  title: "Matthew J Prado Portfolio"
  google-analytics: "G-SRJF0PFMLY"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - text: Projects
        menu:
          - href: digitalprojects.qmd
            text: "Project 1: Trauma Resource Institute Analytics Project"
            text: "Project 2: Trauma Resource Institute Marketing Strategy Project"
          - href: analyticsprojects.qmd
            text: "Project 3: Customer Satisfaction of Students Eating at Cal Poly Pomona Restaurants"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



