project:
  type: website
  output-dir: docs

website:
  title: "Matthew J Prado Portfolio"
  google-analytics: "G-SRJF0PFMLY"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - text: Projects
        menu:
          - href: digitalprojects.qmd
            text: "Digital Marketing Projects"
          - href: analyticsprojects.qmd
            text: "Marketing Analytics Projects"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



